print('ola mundo')
print('eu quero comer pastel')
print('de preferencia de carne seca com queijo')
print('e quero tomar um caldo de cana com limão')
print('quero muito sair para bailar')
print('hoje vou para a festa da empresa e vou comer de mais')
print('vou dar prejuizo pra eles')
print('pelo menos eu vou conhecer os meus colegas de home office')
print ('para falar a verdade estou até ansiosa para ir a essa festa')
print('O dress coud da festa é de época e não faço ideia do que eu vou vestir')
print('é isso amigos um grande beijão')